# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HarmonyProjectIOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'AFNetworking'
    pod 'Masonry'

  # Pods for HarmonyProjectIOS

  target 'HarmonyProjectIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HarmonyProjectIOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
